# Generated by Django 5.2.8 on 2025-12-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
